"use client";import{useEffect,useRef,useState}from"react";
function Photo({src,name,onChange,onRemove}:{src?:string|null,name:string,onChange:(v:string)=>void,onRemove:()=>void}){const ref=useRef<HTMLInputElement>(null);function pick(e:any){const f=e.target.files?.[0];if(!f)return;if(!["image/jpeg","image/png"].includes(f.type)){alert("Please choose a JPEG or PNG image.");return}if(f.size>2500000){alert("Profile picture must be 2.5 MB or smaller.");return}const r=new FileReader();r.onload=()=>onChange(String(r.result));r.readAsDataURL(f)}return <div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:42,height:42,borderRadius:"50%",overflow:"hidden",background:"#e5e7eb",display:"grid",placeItems:"center",fontWeight:700}}>{src?<img src={src} alt={name} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:name?.charAt(0).toUpperCase()}</div><input ref={ref} type="file" accept="image/jpeg,image/png" hidden onChange={pick}/><button type="button" className="secondary" onClick={()=>ref.current?.click()}>{src?"Change Photo":"Add Photo"}</button>{src&&<button type="button" className="secondary" onClick={onRemove}>Remove</button>}</div>}
export default function Teachers(){const[rows,setRows]=useState<any[]>([]),[countries,setCountries]=useState<any[]>([]),[editing,setEditing]=useState<string|null>(null),[editCountry,setEditCountry]=useState(""),[editTimezone,setEditTimezone]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[countryCode,setCountryCode]=useState(""),[timezone,setTimezone]=useState(""),[photo,setPhoto]=useState<string|null>(null);
async function load(){const x=await fetch("/api/teachers",{cache:"no-store"});if(x.ok)setRows(await x.json())}useEffect(()=>{load();fetch("/api/timezone-options",{cache:"no-store"}).then(r=>r.json()).then(j=>setCountries(j.countries||[]))},[]);
const selected=countries.find(c=>c.id===countryCode);
function selectCountry(v:string){const c=countries.find(x=>x.id===v);setCountryCode(v);setTimezone(c?.timezones?.[0]?.name||"")}
async function add(){const x=await fetch("/api/teachers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,password,countryCode,timezone,profileImage:photo})});if(x.ok){setName("");setEmail("");setPassword("");setCountryCode("");setTimezone("");setPhoto(null);load()}else{const j=await x.json().catch(()=>({}));alert(j.error||"Unable to create teacher.")}}
async function toggle(r:any){const x=await fetch("/api/teachers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:r.id,active:!r.active})});if(x.ok)load();else alert((await x.json().catch(()=>({}))).error||"Unable to change status.")}
function startEdit(r:any){setEditing(r.id);setEditCountry(r.country_code||"");setEditTimezone(r.timezone||"")}
function cancelEdit(){setEditing(null);setEditCountry("");setEditTimezone("")}
function changeEditCountry(v:string){const c=countries.find(x=>x.id===v);setEditCountry(v);setEditTimezone(c?.timezones?.some((z:any)=>z.name===editTimezone)?editTimezone:(c?.timezones?.[0]?.name||""))}
async function saveLocation(r:any){if(!editCountry||!editTimezone){alert("Please choose a country and time zone.");return}const x=await fetch("/api/teachers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:r.id,countryCode:editCountry,timezone:editTimezone})});if(x.ok){cancelEdit();load()}else alert((await x.json().catch(()=>({}))).error||"Unable to update teacher location.")}
async function photoUpdate(r:any,v:string|null){const x=await fetch("/api/teachers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(v?{id:r.id,profileImage:v}:{id:r.id,removeProfileImage:true})});if(x.ok)load();else alert((await x.json().catch(()=>({}))).error||"Unable to update profile picture.")}
async function remove(r:any){if(!confirm("Delete "+r.name+"? Their login access will be permanently disabled. Their lessons, recordings, reports, scores and teaching history will be preserved in Deleted Teachers for Admin only."))return;const x=await fetch("/api/teachers?id="+encodeURIComponent(r.id),{method:"DELETE"});const j=await x.json().catch(()=>({}));if(x.ok)load();else alert(j.error||"Unable to delete teacher.")}
return <main className="main"><h1>Add/Remove Teacher</h1><div className="card"><h3>Add Teacher</h3><div className="form-grid"><input className="input" placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input" placeholder="Temporary password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><select className="input" value={countryCode} onChange={e=>selectCountry(e.target.value)}><option value="">Choose teacher country</option>{countries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="input" value={timezone} onChange={e=>setTimezone(e.target.value)} disabled={!selected}><option value="">Choose time zone</option>{selected?.timezones?.map((z:any)=><option key={z.name} value={z.name}>{z.name} ({z.offset})</option>)}</select><div><div className="muted small" style={{marginBottom:6}}>Profile picture — Admin only</div><Photo src={photo} name={name} onChange={setPhoto} onRemove={()=>setPhoto(null)}/></div></div><button className="primary compact-btn" onClick={add}>Create teacher</button></div><div className="section"><table className="table"><thead><tr><th>Photo</th><th>Name</th><th>Email</th><th>Country</th><th>Time Zone</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Photo src={r.profile_image} name={r.name} onChange={v=>photoUpdate(r,v)} onRemove={()=>photoUpdate(r,null)}/></td><td>{r.name}</td><td>{r.email}</td><td>{countries.find(c=>c.id===r.country_code)?.name||r.country_code||"—"}</td><td>{r.timezone||"—"}</td><td><span style={{fontWeight:700}}>{r.active?"Active":"Inactive"}</span></td><td>{editing===r.id?<div style={{display:"grid",gap:6,minWidth:240}}><select className="input" value={editCountry} onChange={e=>changeEditCountry(e.target.value)}><option value="">Choose country</option>{countries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="input" value={editTimezone} onChange={e=>setEditTimezone(e.target.value)} disabled={!editCountry}><option value="">Choose time zone</option>{countries.find(c=>c.id===editCountry)?.timezones?.map((z:any)=><option key={z.name} value={z.name}>{z.name} ({z.offset})</option>)}</select><div><button className="primary" onClick={()=>saveLocation(r)}>Save</button>{" "}<button className="secondary" onClick={cancelEdit}>Cancel</button></div></div>:<><button className="secondary" onClick={()=>startEdit(r)}>Change Country / Time Zone</button>{" "}<button className="secondary" onClick={()=>toggle(r)}>{r.active?"Set Inactive":"Set Active"}</button>{" "}<button className="secondary" onClick={()=>remove(r)}>Delete</button></>}</td></tr>)}</tbody></table></div></main>}