import{NextResponse}from"next/server";import{query}from"@/lib/db";import{requireRole}from"@/lib/auth";
export async function GET(){try{const s=await requireRole(["ADMIN","TEACHER","STUDENT"]);await query("ALTER TABLE cancellation_requests ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now()");const q=s.role==="ADMIN"?"SELECT cr.*,l.starts_at,l.ends_at,l.status AS lesson_status,l.room_code,t.full_name teacher_name,st.full_name student_name,u.full_name requester_name FROM cancellation_requests cr JOIN lessons l ON l.id=cr.lesson_id JOIN users t ON t.id=l.teacher_id JOIN users st ON st.id=l.student_id JOIN users u ON u.id=cr.requested_by ORDER BY cr.created_at DESC":"SELECT cr.*,l.starts_at,l.ends_at,l.status AS lesson_status,l.room_code,t.full_name teacher_name,st.full_name student_name,u.full_name requester_name FROM cancellation_requests cr JOIN lessons l ON l.id=cr.lesson_id JOIN users t ON t.id=l.teacher_id JOIN users st ON st.id=l.student_id JOIN users u ON u.id=cr.requested_by WHERE cr.requested_by=$1 ORDER BY cr.created_at DESC";const r=await query(q,s.role==="ADMIN"?[]:[s.id]);return NextResponse.json(r.rows)}catch{return NextResponse.json({error:"Could not load cancellation requests."},{status:500})}}
export async function POST(req:Request){const s=await requireRole(["TEACHER","STUDENT"]);const{lessonId,reason}=await req.json();if(!lessonId)return NextResponse.json({error:"Lesson is required."},{status:400});if(!reason||!String(reason).trim())return NextResponse.json({error:"A cancellation reason is required."},{status:400});const lesson=await query("SELECT id,status,teacher_id,student_id FROM lessons WHERE id=$1",[lessonId]);if(!lesson.rowCount)return NextResponse.json({error:"Lesson not found."},{status:404});const l=lesson.rows[0];if(s.role==="TEACHER"&&l.teacher_id!==s.id)return NextResponse.json({error:"Lesson not found."},{status:404});if(s.role==="STUDENT"&&l.student_id!==s.id)return NextResponse.json({error:"Lesson not found."},{status:404});if(l.status==="CANCELLED")return NextResponse.json({error:"This lesson is already cancelled."},{status:409});
if(s.role==="STUDENT"){
  const full=await query<any>("SELECT l.*,t.email teacher_email,t.full_name teacher_name,st.full_name student_name,mat.title lesson_title FROM lessons l JOIN users t ON t.id=l.teacher_id JOIN users st ON st.id=l.student_id LEFT JOIN LATERAL (SELECT m.title FROM lesson_materials lm JOIN materials m ON m.id=lm.material_id WHERE lm.lesson_id=l.id LIMIT 1) mat ON true WHERE l.id=$1",[lessonId]);
  const x=full.rows[0];const late=new Date().getTime()>new Date(x.starts_at).getTime()-2*60*60*1000;
  await query("ALTER TABLE lessons ADD COLUMN IF NOT EXISTS student_cancelled_late boolean NOT NULL DEFAULT false");
  await query("ALTER TABLE lessons ADD COLUMN IF NOT EXISTS reminder_24h_ids jsonb NOT NULL DEFAULT '[]'::jsonb");
  await query("ALTER TABLE lessons ADD COLUMN IF NOT EXISTS reminder_1h_ids jsonb NOT NULL DEFAULT '[]'::jsonb");
  await query("UPDATE lessons SET status='CANCELLED',student_cancelled_late=$2 WHERE id=$1",[lessonId,late]);
  for(const id of [...(x.reminder_24h_ids||[]),...(x.reminder_1h_ids||[])])await cancelScheduledEmail(String(id));
  await query("INSERT INTO cancellation_requests(lesson_id,requested_by,reason,status,reviewed_at) VALUES($1,$2,$3,'APPROVED',now()) ON CONFLICT(lesson_id) DO UPDATE SET requested_by=EXCLUDED.requested_by,reason=EXCLUDED.reason,status='APPROVED',reviewed_at=now()",[lessonId,s.id,String(reason).trim()]);
  await sendStudentCancellationTeacherEmail({teacherEmail:x.teacher_email,teacherName:x.teacher_name,studentName:x.student_name,startsAt:x.starts_at,lessonTitle:x.lesson_title||"English Lesson",lessonType:x.lesson_type}).catch(e=>console.error("Student cancellation email failed",e));
  return NextResponse.json({ok:true,status:"CANCELLED",late});
}
const existing=await query("SELECT id,status FROM cancellation_requests WHERE lesson_id=$1",[lessonId]);if(existing.rowCount&&existing.rows[0].status==="PENDING")return NextResponse.json({error:"A cancellation request is already pending."},{status:409});const r=await query("INSERT INTO cancellation_requests(lesson_id,requested_by,reason) VALUES($1,$2,$3) ON CONFLICT(lesson_id) DO UPDATE SET requested_by=EXCLUDED.requested_by,reason=EXCLUDED.reason,status='PENDING',reviewed_by=NULL,reviewed_at=NULL RETURNING *",[lessonId,s.id,String(reason).trim()]);return NextResponse.json(r.rows[0])}