import{NextResponse}from"next/server";import{query}from"@/lib/db";import{requireRole}from"@/lib/auth";import{sendBookingEmails}from"@/lib/email";
async function chooseNextMaterial(studentId:string,lessonType:string){if(lessonType==="DEMO")return null;const st=await query<any>("SELECT starting_material_id,coalesce(level,'Level 1') level,ferris_wheel_material_id FROM students WHERE user_id=$1",[studentId]);const row=st.rows[0];if(!row)return null;if(lessonType==="FERRIS_WHEEL"&&row.ferris_wheel_material_id){const m=await query<any>("SELECT * FROM materials WHERE id=$1",[row.ferris_wheel_material_id]);return m.rows[0]||null}const startId=row.starting_material_id,studentLevel=row.level||"Level 1";const mats=await query<any>("SELECT id,title,folder,sequence_no FROM materials WHERE folder NOT IN ('Demo','Ferris Wheel') ORDER BY NULLIF(regexp_replace(folder,'[^0-9]','','g'),'')::int NULLS LAST,sequence_no,title");if(!mats.rowCount)return null;const used=await query<any>("SELECT DISTINCT lm.material_id FROM lesson_materials lm JOIN lessons l ON l.id=lm.lesson_id WHERE l.student_id=$1 AND l.status<>'CANCELLED' AND l.lesson_type NOT IN ('DEMO','FERRIS_WHEEL')",[studentId]);const usedIds=new Set(used.rows.map((x:any)=>x.material_id));let startIndex=0;if(startId){const i=mats.rows.findIndex((m:any)=>m.id===startId);if(i>=0)startIndex=i}else{const i=mats.rows.findIndex((m:any)=>m.folder===studentLevel);if(i>=0)startIndex=i}return mats.rows.slice(startIndex).find((m:any)=>!usedIds.has(m.id))||null}
async function ensureLessonEmailColumns(){await query("ALTER TABLE lessons ADD COLUMN IF NOT EXISTS reminder_24h_ids jsonb NOT NULL DEFAULT '[]'::jsonb");await query("ALTER TABLE lessons ADD COLUMN IF NOT EXISTS reminder_1h_ids jsonb NOT NULL DEFAULT '[]'::jsonb");await query("ALTER TABLE lessons ADD COLUMN IF NOT EXISTS student_cancelled_late boolean NOT NULL DEFAULT false")}
export async function GET(req:Request){await ensureLessonEmailColumns();const s=await requireRole(["ADMIN","TEACHER","STUDENT"]);await query("UPDATE lessons SET class_number=nextval('lesson_class_number_seq') WHERE class_number IS NULL");await query("UPDATE lessons SET class_id='GEAO'||to_char(starts_at AT TIME ZONE 'Asia/Shanghai','YYYYMMDD')||'/'||lpad(class_number::text,3,'0') WHERE class_id IS NULL AND class_number IS NOT NULL");
if(s.role==="ADMIN"){
  await query(`WITH presence AS (
    SELECT l.id,
      min(cs.created_at) FILTER (WHERE cs.sender_id=l.teacher_id AND cs.payload->>'type'='presence') AS teacher_first,
      min(cs.created_at) FILTER (WHERE cs.sender_id=l.student_id AND cs.payload->>'type'='presence') AS student_first
    FROM lessons l
    LEFT JOIN classroom_signals cs ON cs.room_code=l.room_code
    WHERE l.status='SCHEDULED' AND l.ends_at<=now()
    GROUP BY l.id
  )
  UPDATE lessons l
  SET status=CASE
    WHEN p.teacher_first IS NULL AND p.student_first IS NULL THEN 'MISSED_BY_TEACHER_AND_STUDENT'
    WHEN p.teacher_first IS NULL THEN 'MISSED_BY_TEACHER'
    WHEN p.student_first IS NULL THEN 'NO_SHOW'
    ELSE 'COMPLETED'
  END
  FROM presence p
  WHERE l.id=p.id AND l.status='SCHEDULED'`);
}
let q="SELECT l.*,t.full_name teacher_name,st.full_name student_name,coalesce(si.level,'Beginner') student_level,si.age student_age,si.ferris_wheel_material_id,mat.material_title FROM lessons l JOIN users t ON t.id=l.teacher_id JOIN users st ON st.id=l.student_id LEFT JOIN students si ON si.user_id=st.id LEFT JOIN LATERAL (SELECT m.title material_title FROM lesson_materials lm JOIN materials m ON m.id=lm.material_id WHERE lm.lesson_id=l.id LIMIT 1) mat ON true",v:any[]=[];
const params=new URL(req.url).searchParams;if(s.role==="TEACHER"){q+=" WHERE l.teacher_id=$1";v=[s.id]}if(s.role==="STUDENT"){q+=" WHERE l.student_id=$1";v=[s.id]}if(s.role==="ADMIN"){
  q+=" WHERE t.deleted_at IS NULL AND st.deleted_at IS NULL";
  const tz=process.env.SCHOOL_TIMEZONE||"Africa/Johannesburg";
  const startDate=params.get("startDate"),endDate=params.get("endDate"),teacherId=params.get("teacherId"),studentId=params.get("studentId");
  if(startDate){v.push(startDate);q+=" AND ((l.starts_at AT TIME ZONE '"+tz+"')::date >= $"+v.length+"::date)"}
  if(endDate){v.push(endDate);q+=" AND ((l.starts_at AT TIME ZONE '"+tz+"')::date <= $"+v.length+"::date)"}
  if(teacherId){v.push(teacherId);q+=" AND l.teacher_id=$"+v.length}
  if(studentId){v.push(studentId);q+=" AND l.student_id=$"+v.length}
}else q+=" AND t.deleted_at IS NULL AND st.deleted_at IS NULL";q+=" ORDER BY l.starts_at DESC LIMIT 200";const r=await query(q,v);return NextResponse.json(r.rows)}
export async function POST(req:Request){await ensureLessonEmailColumns();const s=await requireRole(["ADMIN","STUDENT"]);const{teacherId,studentId,startsAt,topic,lessonType="ONE_ON_ONE"}=await req.json();const actualStudentId=s.role==="STUDENT"?s.id:studentId;if(!teacherId||!actualStudentId||!startsAt)return NextResponse.json({error:"Teacher and start time are required."},{status:400});const type=String(lessonType).toUpperCase();if(!["ONE_ON_ONE","DEMO","FERRIS_WHEEL"].includes(type))return NextResponse.json({error:"Invalid lesson type."},{status:400});const start=new Date(startsAt);if(Number.isNaN(start.getTime())||start.getTime()<=Date.now())return NextResponse.json({error:"Please choose a future lesson time."},{status:400});if(start.getMinutes()%30!==0)return NextResponse.json({error:"Lessons must start on the half-hour."},{status:400});const end=new Date(start.getTime()+1800000),tz="Asia/Shanghai";
if(s.role==="STUDENT"){const w=await query("SELECT ((now() AT TIME ZONE $1)::date) today,(((now() AT TIME ZONE $1)::date)+14) max_date",[tz]);const localDate=start.toLocaleDateString("en-CA",{timeZone:tz});if(localDate<w.rows[0].today||localDate>w.rows[0].max_date)return NextResponse.json({error:"Lessons can only be booked within the rolling 14-day booking window."},{status:409});const teacher=await query("SELECT id FROM users WHERE id=$1 AND role='TEACHER' AND active=true",[teacherId]);if(!teacher.rowCount)return NextResponse.json({error:"Teacher not found."},{status:404});if(type==="DEMO"){const st=await query("SELECT coalesce(demo_enabled,true) demo_enabled FROM students WHERE user_id=$1",[actualStudentId]);if(st.rows[0]?.demo_enabled===false)return NextResponse.json({error:"Demo lessons are not enabled for this student."},{status:403})}if(type==="FERRIS_WHEEL"){const st=await query("SELECT ferris_wheel_material_id FROM students WHERE user_id=$1",[actualStudentId]);if(!st.rows[0]?.ferris_wheel_material_id)return NextResponse.json({error:"Ferris Wheel has not been linked to this student."},{status:403})}const one=await query("SELECT id FROM teacher_availability_slots WHERE teacher_id=$1 AND slot_date=$2 AND start_time=$3 AND admin_opened=true",[teacherId,localDate,start.toLocaleTimeString("en-GB",{timeZone:tz,hour:"2-digit",minute:"2-digit",hour12:false})]);if(!one.rowCount)return NextResponse.json({error:"That exact 30-minute slot has not been opened by the teacher."},{status:409});const ex=await query("SELECT id FROM teacher_availability_exceptions WHERE teacher_id=$1 AND slot_date=(($2::timestamptz AT TIME ZONE $3)::date) AND start_time=(($2::timestamptz AT TIME ZONE $3)::time)",[teacherId,start.toISOString(),tz]);if(ex.rowCount)return NextResponse.json({error:"That slot is no longer available."},{status:409})}
const conflict=await query("SELECT id FROM lessons WHERE (teacher_id=$1 OR student_id=$2) AND status<>'CANCELLED' AND starts_at<$3 AND ends_at>$4",[teacherId,actualStudentId,end,start]);if(conflict.rowCount)return NextResponse.json({error:"That 30-minute slot conflicts with another lesson."},{status:409});
const room="gea-"+crypto.randomUUID();const r=await query("INSERT INTO lessons(teacher_id,student_id,starts_at,ends_at,room_code,topic,lesson_type) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[teacherId,actualStudentId,start,end,room,topic||"",type]);
const classId='GEAO'+start.toLocaleDateString('en-CA',{timeZone:tz}).replaceAll('-','')+'/'+String(r.rows[0].class_number).padStart(3,'0');
await query("UPDATE lessons SET class_id=$1 WHERE id=$2",[classId,r.rows[0].id]);
r.rows[0].class_id=classId;const material=await chooseNextMaterial(actualStudentId,type);if(material)await query("INSERT INTO lesson_materials(lesson_id,material_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[r.rows[0].id,material.id]);
const people=await query("SELECT id,email,full_name,role FROM users WHERE id=ANY($1::uuid[])",[[teacherId,actualStudentId]]);const teacher=people.rows.find((p:any)=>p.id===teacherId),student=people.rows.find((p:any)=>p.id===actualStudentId);if(teacher&&student){sendBookingEmails({teacherEmail:teacher.email,teacherName:teacher.full_name,studentEmail:student.email,studentName:student.full_name,startsAt:r.rows[0].starts_at,roomCode:r.rows[0].room_code,classId:r.rows[0].class_id,lessonTitle:material?.title||topic||"English Lesson",lessonType:type}).then(async ids=>{if(ids)await query("UPDATE lessons SET reminder_24h_ids=$1::jsonb,reminder_1h_ids=$2::jsonb WHERE id=$3",[JSON.stringify(ids.reminder24hIds||[]),JSON.stringify(ids.reminder1hIds||[]),r.rows[0].id])}).catch(e=>console.error("Booking email failed",e));}return NextResponse.json(r.rows[0])}