"use client";
import{useEffect,useMemo,useState}from"react";
function pad(n:number){return String(n).padStart(2,"0")}
function addDays(date:Date,n:number){const d=new Date(date);d.setDate(d.getDate()+n);return d}
function dateKey(d:Date){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function timeSlots(start:string,end:string){const out:string[]=[];const p=String(start).slice(0,5).split(":").map(Number),e=String(end).slice(0,5).split(":").map(Number);let cur=p[0]*60+p[1],finish=e[0]*60+e[1];while(cur+30<=finish){out.push(`${pad(Math.floor(cur/60))}:${pad(cur%60)}`);cur+=30}return out}
function labelDate(value:string){const d=new Date(value+"T12:00:00");return{day:d.toLocaleDateString("en-US",{weekday:"short"}),date:d.toLocaleDateString("en-US",{month:"short",day:"numeric"})}}
export default function BookLesson(){
 const[teachers,setTeachers]=useState<any[]>([]),[teacherId,setTeacherId]=useState(""),[availability,setAvailability]=useState<any[]>([]),[date,setDate]=useState(""),[time,setTime]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 const base=new Date();base.setHours(12,0,0,0);const minDate=dateKey(base),maxDate=dateKey(addDays(base,14));
 useEffect(()=>{fetch("/api/availability").then(r=>r.ok?r.json():[]).then(setTeachers).catch(()=>setTeachers([]))},[]);
 useEffect(()=>{setDate("");setTime("");setMessage("");if(!teacherId){setAvailability([]);return}fetch("/api/availability?teacherId="+encodeURIComponent(teacherId)).then(r=>r.ok?r.json():[]).then(setAvailability).catch(()=>setAvailability([]))},[teacherId]);
 const availableByDate=useMemo(()=>{const map=new Map<string,Set<string>>();for(const a of availability){if(a.slot_date){const key=String(a.slot_date).slice(0,10);if(key>=minDate&&key<=maxDate){if(!map.has(key))map.set(key,new Set());map.get(key)!.add(String(a.start_time).slice(0,5))}}else if(Number.isInteger(a.day_of_week)){for(let i=0;i<=14;i++){const d=addDays(base,i);if(d.getDay()===a.day_of_week){const key=dateKey(d);if(!map.has(key))map.set(key,new Set());for(const t of timeSlots(a.start_time,a.end_time))map.get(key)!.add(t)}}}}return map},[availability,minDate,maxDate]);
 const dates=Array.from(availableByDate.keys()).sort(),times=date?Array.from(availableByDate.get(date)||[]).sort():[];
 async function book(){setMessage("Booking…");if(!teacherId||!date||!time){setMessage("Please choose an available date and time.");return}setLoading(true);try{const x=await fetch("/api/lessons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teacherId,startsAt:date+"T"+time+":00",topic:"English lesson"})});const j=await x.json();setMessage(x.ok?"Lesson booked successfully.":j.error||"Could not book lesson.");if(x.ok)setTime("")}catch{setMessage("Could not book lesson. Please try again.")}finally{setLoading(false)}}
 return <main className="main"><h1>Book an English Lesson</h1><p className="muted">Choose a teacher and then see only the exact dates and 30-minute times that teacher has opened.</p><div className="card"><label>Teacher<select className="input" value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Choose a teacher</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{teacherId&&<div className="card"><strong>Available dates for {teachers.find(t=>t.id===teacherId)?.name||"this teacher"}</strong><p className="muted">Only days with at least one open lesson are shown.</p>{dates.length?<div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:10}}>{dates.map(d=>{const l=labelDate(d),selected=d===date;return <button key={d} type="button" onClick={()=>{setDate(d);setTime("")}} style={{padding:"10px 14px",borderRadius:8,border:"1px solid #93c5fd",background:selected?"#4c1d95":"#dbeafe",color:selected?"white":"#1e40af",fontWeight:600,cursor:"pointer"}}><div>{l.day}</div><div>{l.date}</div><small>{availableByDate.get(d)?.size||0} time{(availableByDate.get(d)?.size||0)===1?"":"s"}</small></button>})}</div>:<div className="muted">This teacher has not published any available lessons in the next 14 days.</div>}</div>}{teacherId&&date&&<div className="card"><strong>Exact available times — {labelDate(date).day}, {labelDate(date).date}</strong><p className="muted">Each button is one 30-minute lesson.</p>{times.length?<div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:10}}>{times.map(t=><button key={t} type="button" className="primary" onClick={()=>setTime(t)}>{t}</button>)}</div>:<div className="muted">No open times remain for this date.</div>}{time&&<p className="muted">Selected start time: {time} (30 minutes)</p>}</div>}<button className="primary" disabled={loading||!teacherId||!date||!time} onClick={book}>{loading?"Booking…":"Book 30-minute lesson"}</button>{message&&<p className="muted">{message}</p>}</div></main>
}