"use client";import{useEffect,useState}from"react";
export default function BookLesson(){
 const[teachers,setTeachers]=useState<any[]>([]),[teacherId,setTeacherId]=useState(""),[availability,setAvailability]=useState<any[]>([]),[date,setDate]=useState(""),[time,setTime]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/availability").then(r=>r.ok?r.json():[]).then(setTeachers)},[]);
 useEffect(()=>{if(teacherId)fetch("/api/availability?teacherId="+encodeURIComponent(teacherId)).then(r=>r.json()).then(setAvailability);else setAvailability([])},[teacherId]);
 const selectedDay=date?new Date(date+"T12:00:00").getDay():-1;
 const windows=availability.filter(a=>a.day_of_week===selectedDay);function slots(){const out:string[]=[];for(const w of windows){const p=String(w.start_time).slice(0,5).split(":").map(Number),e=String(w.end_time).slice(0,5).split(":").map(Number);let cur=p[0]*60+p[1],end=e[0]*60+e[1];while(cur+30<=end){out.push(String(Math.floor(cur/60)).padStart(2,"0")+":"+String(cur%60).padStart(2,"0"));cur+=30}}return out}
 async function book(){setMessage("Booking…");if(!teacherId||!date||!time){setMessage("Please choose a teacher, date and time.");return}const x=await fetch("/api/lessons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teacherId,startsAt:date+"T"+time+":00",topic:"English lesson"})});const j=await x.json();setMessage(x.ok?"Lesson booked successfully.":j.error||"Could not book lesson.");}
 return <main className="main"><h1>Book an English Lesson</h1><p className="muted">Choose a teacher and a 30-minute time within their published availability.</p><div className="card"><label>Teacher<select className="input" value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Choose a teacher</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Date<input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{teacherId&&date&&<div className="card"><strong>Available 30-minute slots</strong>{windows.length?<div>{slots().map(t=><button key={t} type="button" className="primary" style={{margin:"6px"}} onClick={()=>setTime(t)}>{t}</button>)}</div>:<div className="muted">This teacher has not published availability for this day.</div>}{time&&<p className="muted">Selected start time: {time} (30 minutes)</p>}</div>}<button className="primary" onClick={book}>Book 30-minute lesson</button>{message&&<p className="muted">{message}</p>}</div></main>
}