"use client";import{useEffect,useState}from"react";

export default function Materials(){
 const[rows,setRows]=useState<any[]>([]),[lessons,setLessons]=useState<any[]>([]),[lessonId,setLessonId]=useState(""),[materialId,setMaterialId]=useState(""),[assigned,setAssigned]=useState<any[]>([]),[role,setRole]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[url,setUrl]=useState(""),[level,setLevel]=useState(""),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState("");
 async function load(){const me=await fetch("/api/me").then(r=>r.json());setRole(me.user?.role||"");const x=await fetch("/api/materials",{cache:"no-store"});if(x.ok)setRows(await x.json());if(me.user?.role==="ADMIN"){const l=await fetch("/api/lessons",{cache:"no-store"});if(l.ok)setLessons(await l.json())}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(!lessonId){setAssigned([]);return}fetch("/api/lesson-materials?lessonId="+encodeURIComponent(lessonId),{cache:"no-store"}).then(r=>r.ok?r.json():[]).then(setAssigned)},[lessonId]);
 async function add(){
  setMessage("Saving…");
  let contentData="",mimeType="";
  if(file){if(file.size>9*1024*1024){setMessage("Please choose a file smaller than 9 MB.");return}contentData=await new Promise<string>((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.onerror=reject;fr.readAsDataURL(file)});mimeType=file.type}
  const x=await fetch("/api/materials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,description,url,level,contentData,mimeType})});
  const j=await x.json();if(x.ok){setTitle("");setDescription("");setUrl("");setLevel("");setFile(null);setMessage("Material saved.");load()}else setMessage(j.error||"Could not save material.")}
 async function allocate(){if(!lessonId||!materialId)return;const r=await fetch("/api/lesson-materials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({lessonId,materialId})});if(r.ok){setMaterialId("");const x=await fetch("/api/lesson-materials?lessonId="+encodeURIComponent(lessonId),{cache:"no-store"});if(x.ok)setAssigned(await x.json())}}async function unallocate(id:string){const r=await fetch("/api/lesson-materials",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({lessonId,materialId:id})});if(r.ok)setAssigned(v=>v.filter(x=>x.id!==id))}
 return <main className="main"><h1>Lesson Materials</h1><p className="muted">Materials allocated by the school are available here. Admin manages, uploads, and assigns all lesson materials. Teachers and students can open the materials allocated to them.</p>
 {role==="ADMIN"&&<div className="card"><h3>Admin Material Management</h3><p className="muted">You control which materials are used by the school. Teachers do not approve or allocate materials.</p><input className="input" placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/><input className="input" placeholder="Level (e.g. Beginner)" value={level} onChange={e=>setLevel(e.target.value)}/><input className="input" placeholder="Unit / lesson description" value={description} onChange={e=>setDescription(e.target.value)}/><label className="input">Upload PDF/lesson file <input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><input className="input" placeholder="Optional external URL" value={url} onChange={e=>setUrl(e.target.value)}/><button className="primary" onClick={add}>Upload material</button>{message&&<div className="muted">{message}</div>}</div>}
 <div className="section">{rows.map(r=><div className="card" key={r.id} style={{marginBottom:12}}><h3>{r.title}</h3><p>{r.description}</p><div className="muted">{r.level||"Uncategorised"}</div>{r.content_data?<span className="muted">Uploaded lesson file</span>:r.url?<span className="muted">External material</span>:<span className="muted">No file attached</span>}</div>)}</div></main>
}