"use client";import{useEffect,useState}from"react";
export default function Students(){const[rows,setRows]=useState<any[]>([]),[materials,setMaterials]=useState<any[]>([]),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[level,setLevel]=useState("Level 1"),[age,setAge]=useState(""),[startingMaterialId,setStartingMaterialId]=useState("");
async function load(){const[x,m]=await Promise.all([fetch("/api/students",{cache:"no-store"}),fetch("/api/materials",{cache:"no-store"})]);if(x.ok)setRows(await x.json());if(m.ok)setMaterials(await m.json())}useEffect(()=>{load()},[]);
const grouped=materials.reduce((a,m)=>{const k=m.folder||m.level||"Uncategorised";(a[k]??=[]).push(m);return a},{} as Record<string,any[]>);
async function add(){const x=await fetch("/api/students",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,password,level,age,startingMaterialId:startingMaterialId||null})});if(x.ok){setName("");setEmail("");setPassword("");setAge("");setStartingMaterialId("");load()}else{const j=await x.json().catch(()=>({}));alert(j.error||"Unable to create student.")}}
async function toggle(r:any){const x=await fetch("/api/students",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:r.id,active:!r.active})});if(x.ok)load();else{const j=await x.json().catch(()=>({}));alert(j.error||"Unable to change status.")}}
async function remove(r:any){if(!confirm("Delete this student permanently? Their lessons, recordings and history will also be deleted. Choose Inactive instead if you want to keep their records."))return;const x=await fetch("/api/students?id="+encodeURIComponent(r.id),{method:"DELETE"});const j=await x.json().catch(()=>({}));if(x.ok)load();else alert(j.error||"Unable to delete student.")}
return <main className="main"><div className="topbar"><div><h1>Students</h1><p className="muted">Create students and choose where their curriculum should begin.</p></div></div>
<div className="card"><h3>New Student</h3><div className="form-grid"><input className="input" placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input" placeholder="Temporary password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><input className="input" placeholder="Age" type="number" min="1" max="120" value={age} onChange={e=>setAge(e.target.value)}/><select className="input" value={level} onChange={e=>setLevel(e.target.value)}><option>Level 1</option><option>Level 2</option><option>Level 3</option><option>Level 4</option><option>Level 5</option><option>Beginner</option></select><select className="input" value={startingMaterialId} onChange={e=>setStartingMaterialId(e.target.value)}><option value="">Starting material — first lesson in level</option>{Object.entries(grouped).map(([folder,list]:any)=><optgroup key={folder} label={folder}>{list.sort((a:any,b:any)=>a.sequence_no-b.sequence_no).map((m:any)=><option key={m.id} value={m.id}>{String(m.sequence_no).padStart(2,"0")} — {m.title}</option>)}</optgroup>)}</select></div><button className="primary compact-btn" onClick={add}>Create student</button><p className="muted small">The selected material becomes the student's starting point. Future bookings automatically receive the next lesson.</p></div>
<div className="section"><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Level</th><th>Starting Material</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.email}</td><td>{r.level}</td><td>{r.starting_material||"Auto from level"}</td><td><span className="status-dot"/>{r.active?"Active":"Inactive"}</td><td><button className="secondary" onClick={()=>toggle(r)}>{r.active?"Set Inactive":"Set Active"}</button>{" "}<button className="secondary" onClick={()=>remove(r)}>Delete</button></td></tr>)}</tbody></table></div></main>}