"use client";
import{useEffect,useMemo,useState}from"react";import Link from"next/link";
const dayNames=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],pad=(n:number)=>String(n).padStart(2,"0"),addMinutes=(t:string,m:number)=>{const p=t.split(":").map(Number),v=p[0]*60+p[1]+m;return pad(Math.floor(v/60)%24)+":"+pad(v%60)},fmtDate=(d:Date)=>d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());
export default function Availability(){
 const today=useMemo(()=>{const d=new Date();d.setHours(12,0,0,0);return d},[]),maxDate=useMemo(()=>{const d=new Date(today);d.setDate(d.getDate()+14);return d},[today]);
 const[slots,setSlots]=useState<any[]>([]),[lessons,setLessons]=useState<any[]>([]),[busy,setBusy]=useState(""),[selected,setSelected]=useState<any>(null),[materials,setMaterials]=useState<any[]>([]),[records,setRecords]=useState<any[]>([]),[recordings,setRecordings]=useState<any[]>([]),[openMaterial,setOpenMaterial]=useState<any>(null);
 const[week,setWeek]=useState(()=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-d.getDay());return d});
 async function load(){try{const[a,l]=await Promise.all([fetch("/api/availability",{cache:"no-store"}),fetch("/api/lessons",{cache:"no-store"})]);if(a.ok)setSlots(await a.json());if(l.ok)setLessons(await l.json())}catch{}}
 useEffect(()=>{load();const refresh=()=>load();window.addEventListener("pageshow",refresh);window.addEventListener("visibilitychange",refresh);return()=>{window.removeEventListener("pageshow",refresh);window.removeEventListener("visibilitychange",refresh)}},[]);
 const dates=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(week);d.setDate(week.getDate()+i);return d}),[week]);
 const slotData=(date:string,time:string)=>{const dt=new Date(date+"T"+time+":00"),end=new Date(dt.getTime()+1800000);const lesson=lessons.find(l=>l.status!=="CANCELLED"&&new Date(l.starts_at)<end&&new Date(l.ends_at)>dt);const slot=slots.find(s=>s.slot_date===date&&String(s.start_time).slice(0,5)===time);return{lesson,slot}};
 async function openBooked(lesson:any){setSelected(lesson);setMaterials([]);setRecords([]);setRecordings([]);try{const[m,r,rec]=await Promise.all([fetch("/api/lesson-materials?lessonId="+encodeURIComponent(lesson.id),{cache:"no-store"}),fetch("/api/records",{cache:"no-store"}),fetch("/api/recordings",{cache:"no-store"})]);if(m.ok)setMaterials(await m.json());if(r.ok)setRecords((await r.json()).filter((x:any)=>x.student_name===lesson.student_name&&x.lesson_id!==lesson.id));if(rec.ok)setRecordings((await rec.json()).filter((x:any)=>x.student_name===lesson.student_name&&x.lesson_id!==lesson.id))}catch{}}
 async function closeFuture(){if(!confirm("Close all future unbooked slots? Already booked lessons will NOT be changed."))return;setBusy("future");try{const x=await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"closeFuture"})});const j=await x.json();if(!x.ok)alert(j.error||"Could not close future slots.");else{alert((j.closed||0)+" future unbooked slot(s) closed. Booked lessons were left untouched.");load()}}finally{setBusy("")}}
 async function openSlot(date:string,time:string){const key=date+time;setBusy(key);try{const x=await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slotDate:date,startTime:time})});const text=await x.text();let j:any={};try{j=JSON.parse(text)}catch{}if(!x.ok)alert(j.error||("Could not open slot. Server returned "+x.status));else setSlots(prev=>prev.some(s=>s.slot_date===date&&String(s.start_time).slice(0,5)===time)?prev:[...prev,{id:j.id,slot_date:date,start_time:time,end_time:addMinutes(time,30)}])}catch{alert("Could not open slot. Please try again.")}finally{setBusy("")}}
 async function cancelSlot(date:string,time:string){setBusy(date+time);const x=await fetch("/api/availability?date="+encodeURIComponent(date)+"&startTime="+encodeURIComponent(time),{method:"DELETE"});const j=await x.json();if(!x.ok)alert(j.error||"Could not cancel slot.");else load();setBusy("")}
 function move(n:number){const d=new Date(week);d.setDate(d.getDate()+n);const maxWeek=new Date(today);maxWeek.setDate(maxWeek.getDate()-maxWeek.getDay());const last=new Date(maxWeek);last.setDate(last.getDate()+14);if(d<maxWeek||d>last)return;setWeek(d)}
 const times=Array.from({length:27},(_,i)=>addMinutes("09:00",i*30));
 const materialSrc=(m:any)=>"/api/lesson-materials/file?lessonId="+encodeURIComponent(selected?.id||"")+"&materialId="+encodeURIComponent(m.id);
 return <main className="main"><div className="topbar"><div><h1>Booking Time</h1><div className="muted">Open each 30-minute slot individually. Click a booked lesson to prepare for the class.</div></div><div><button style={{marginLeft:8}} onClick={()=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-d.getDay());setWeek(d)}}>This Week</button><button style={{marginLeft:8}} onClick={()=>move(7)}>Next Week →</button><button className="secondary" style={{marginLeft:8}} onClick={closeFuture} disabled={busy==="future"}>{busy==="future"?"Closing…":"Close Future Slots"}</button></div></div>
 <div className="card"><strong>Teacher preparation</strong><p className="muted">When a student books a slot, click the purple <b>BOOKED</b> block to see the student's information, Classroom ID and the lesson material selected by the school. Materials are view-only.</p></div>
 <div style={{overflowX:"auto"}}><table className="table" style={{minWidth:1100}}><thead><tr><th style={{minWidth:90}}>Time</th>{dates.map((d,i)=><th key={i} style={{minWidth:135}}>{dayNames[d.getDay()]}<br/>{d.toLocaleDateString("en-US",{month:"2-digit",day:"2-digit"})}</th>)}</tr></thead>
 <tbody>{times.map(t=><tr key={t}><td><strong>{t}</strong></td>{dates.map(d=>{const date=fmtDate(d),sa=addMinutes(t,-360),{lesson,slot}=slotData(date,sa),key=date+sa;const dayOnly=new Date(date+"T12:00:00"),now=new Date(),nowSA=new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",hour:"2-digit",minute:"2-digit",hour12:false}).format(now),todaySA=new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",year:"numeric",month:"2-digit",day:"2-digit"}).format(now),inWindow=dayOnly>=today&&dayOnly<=maxDate,hasPassed=date<todaySA||(date===todaySA&&sa<=nowSA);return <td key={key} style={{verticalAlign:"top"}}><div className="muted" style={{fontSize:12}}>SA {sa}</div>{!inWindow?<div className="muted">Not open yet</div>:hasPassed&&!lesson?<div className="muted">Time passed</div>:lesson?<><button onClick={()=>openBooked(lesson)} style={{background:"#4c1d95",color:"white",fontWeight:700,fontSize:11,padding:"4px 7px",borderRadius:6,border:0,cursor:"pointer"}}>BOOKED</button><div style={{fontSize:12,marginTop:4}}>{lesson.student_name}</div><Link href={"/classroom/"+lesson.room_code}>Join Classroom</Link></>:slot?<><div style={{fontSize:12,fontWeight:700,color:"#60a5fa"}}>OPEN FOR BOOKING</div><button style={{background:"#dbeafe",color:"#1e40af",border:"1px solid #93c5fd",fontSize:11,padding:"4px 7px",borderRadius:6}} onClick={()=>cancelSlot(date,sa)} disabled={busy===key}>{busy===key?"...":"Cancel Slot"}</button></>:<button onClick={()=>openSlot(date,sa)} style={{background:"#f3f4f6",fontSize:11,padding:"4px 7px",borderRadius:6,border:"1px solid #d1d5db"}} disabled={busy===key||!inWindow||hasPassed}>{busy===key?"Opening…":"Book Slot"}</button>}</td>})}</tr>)}</tbody></table></div>
 {selected&&<div onClick={()=>setSelected(null)} style={{position:"fixed",inset:0,zIndex:900,background:"rgba(15,23,42,.65)",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div onClick={e=>e.stopPropagation()} className="card" style={{width:"min(900px,100%)",maxHeight:"90vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2>Classroom Preparation</h2><button onClick={()=>setSelected(null)}>Close</button></div>
 <h3>Information</h3><table className="table"><tbody><tr><td><strong>Course</strong></td><td>{selected.topic||"English lesson"}</td></tr><tr><td><strong>Time</strong></td><td>{new Date(selected.starts_at).toLocaleString("en-ZA",{timeZone:"Africa/Johannesburg"})}</td></tr><tr><td><strong>Classroom ID</strong></td><td><code>{selected.room_code}</code></td></tr></tbody></table>
 <h3>Teaching Material</h3>{materials.length?<div style={{display:"grid",gap:8}}>{materials.map(m=><button key={m.id} onClick={()=>setOpenMaterial(m)} style={{textAlign:"left",padding:12,border:"1px solid #dbeafe",borderRadius:8,background:"#eff6ff",cursor:"pointer"}}>📄 <strong>{m.title}</strong><div className="muted">{m.level||"School material"} • View only</div></button>)}</div>:<p className="muted">No lesson material has been assigned by the school yet.</p>}
 <h3>Student</h3><div className="card"><strong>{selected.student_name}</strong><div>Age: {selected.student_age??"Not set"}</div><div>Level: {selected.student_level||"Beginner"}</div></div>
 <h3>Performance</h3><p className="muted">{records.length?"Previous teacher records are available below.":"No previous performance record is available yet."}</p>
 <h3>Previous Recording</h3>{recordings.length?recordings.slice(0,5).map(r=><div key={r.id} style={{padding:"8px 0"}}>🎥 {new Date(r.starts_at).toLocaleDateString("en-ZA",{timeZone:"Africa/Johannesburg"})} • {Math.round((r.duration_seconds||0)/60)} min</div>):<p className="muted">No previous recordings.</p>}
 <h3>Previous Comments</h3>{records.length?records.slice(0,5).map(r=><div key={r.id} style={{padding:"8px 0",borderBottom:"1px solid #e5e7eb"}}><strong>{new Date(r.updated_at).toLocaleDateString("en-ZA")}</strong><div>{r.notes||"No comment recorded."}</div>{r.homework&&<div className="muted">Homework: {r.homework}</div>}</div>):<p className="muted">No previous comments.</p>}
 <div style={{marginTop:18}}><Link className="primary" href={"/classroom/"+selected.room_code}>Open Classroom</Link></div></div></div>}
 {openMaterial&&selected&&<div onContextMenu={e=>e.preventDefault()} style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(15,23,42,.92)",display:"flex",flexDirection:"column",padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",color:"#fff",marginBottom:10}}><strong>📄 {openMaterial.title}</strong><button onClick={()=>setOpenMaterial(null)}>Close</button></div><div style={{flex:1,background:"#fff",borderRadius:10,overflow:"hidden"}}>{openMaterial.mime_type?.startsWith("image/")?<img src={materialSrc(openMaterial)} draggable={false} onContextMenu={e=>e.preventDefault()} style={{width:"100%",height:"100%",objectFit:"contain"}}/>:<iframe title={openMaterial.title} src={materialSrc(openMaterial)+"#toolbar=0&navpanes=0&scrollbar=1"} sandbox="allow-same-origin allow-scripts" style={{width:"100%",height:"100%",border:0}}/>}</div><div style={{color:"#cbd5e1",fontSize:12,textAlign:"center",paddingTop:8}}>School material • view only • downloading is not provided.</div></div>}</main>
}