"use client";
import{useEffect,useMemo,useState}from"react";
export default function Availability(){
 const[rows,setRows]=useState<any[]>([]),[lessons,setLessons]=useState<any[]>([]),[day,setDay]=useState("1"),[start,setStart]=useState("09:00"),[end,setEnd]=useState("17:00"),[date,setDate]=useState(()=>new Date().toISOString().slice(0,10)),[busy,setBusy]=useState("");
 async function load(){const[a,l]=await Promise.all([fetch("/api/availability"),fetch("/api/lessons")]);if(a.ok)setRows(await a.json());if(l.ok)setLessons(await l.json())}
 useEffect(()=>{load()},[]);
 async function add(){await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dayOfWeek:Number(day),startTime:start,endTime:end})});load()}
 const slots=useMemo(()=>{const dow=new Date(date+"T12:00:00").getDay(),out:any[]=[];for(const r of rows.filter(x=>x.day_of_week===dow)){let [h,m]=String(r.start_time).slice(0,5).split(":").map(Number),[eh,em]=String(r.end_time).slice(0,5).split(":").map(Number);let cur=h*60+m,endm=eh*60+em;while(cur+30<=endm){const t=String(Math.floor(cur/60)).padStart(2,"0")+":"+String(cur%60).padStart(2,"0");out.push({availabilityId:r.id,start:t});cur+=30}}return out},[rows,date]);
 function booked(t:string){const a=new Date(date+"T"+t+":00");const b=new Date(a.getTime()+1800000);return lessons.some(l=>l.status!=="CANCELLED"&&new Date(l.starts_at)<b&&new Date(l.ends_at)>a)}
 async function cancel(slot:any){if(booked(slot.start))return;setBusy(slot.availabilityId+slot.start);const x=await fetch("/api/availability?availabilityId="+encodeURIComponent(slot.availabilityId)+"&date="+encodeURIComponent(date)+"&startTime="+encodeURIComponent(slot.start),{method:"DELETE"});const j=await x.json();if(!x.ok)alert(j.error);else alert("Unbooked slot cancelled for this date.");setBusy("");load()}
 return <main className="main"><h1>Booking Time</h1><div className="card"><p className="muted">Add your recurring teaching availability. Students will see 30-minute slots within these times.</p><select className="input" value={day} onChange={e=>setDay(e.target.value)}>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((x,i)=><option key={x} value={i}>{x}</option>)}</select><input className="input" type="time" step="1800" value={start} onChange={e=>setStart(e.target.value)}/><input className="input" type="time" step="1800" value={end} onChange={e=>setEnd(e.target.value)}/><button className="primary" onClick={add}>Add availability</button></div><div className="section"><h2>Recurring availability</h2><table className="table"><thead><tr><th>Day</th><th>Start</th><th>End</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][r.day_of_week]}</td><td>{String(r.start_time).slice(0,5)}</td><td>{String(r.end_time).slice(0,5)}</td><td><button onClick={async()=>{if(!confirm("Cancel this recurring availability? Any booked lessons in this recurring period must be cancelled through Admin approval first."))return;const x=await fetch("/api/availability",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({availabilityId:r.id})});const j=await x.json();if(!x.ok)alert(j.error);else{alert("Recurring availability cancelled.");load()}}}>Cancel availability</button></td></tr>)}</tbody></table></div><div className="section"><h2>Manage individual slots</h2><p className="muted">Choose a date. You can cancel an unbooked 30-minute slot immediately. A booked slot must go through Admin approval.</p><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><table className="table"><thead><tr><th>Slot</th><th>Status</th><th>Action</th></tr></thead><tbody>{slots.map(s=>{const b=booked(s.start);return <tr key={s.availabilityId+s.start}><td>{s.start}–{String((Number(s.start.slice(0,2))*60+Number(s.start.slice(3))+30)/60|0).padStart(2,"0")}:{String((Number(s.start.slice(3))+30)%60).padStart(2,"0")}</td><td>{b?"BOOKED":"AVAILABLE"}</td><td>{b?<span className="muted">Use Request cancellation on My Session</span>:<button onClick={()=>cancel(s)} disabled={busy===s.availabilityId+s.start}>{busy===s.availabilityId+s.start?"Cancelling…":"Cancel slot"}</button>}</td></tr>})}</tbody></table>{!slots.length&&<p className="muted">No recurring availability for this date.</p>}</div></main>
}