import TeacherShell from "../_components/TeacherShell";
"use client";

import{useEffect,useState}from"react";
import Link from"next/link";

type User={id:string;name:string;email:string;role:"ADMIN"|"TEACHER"|"STUDENT"|"PARENT"};
type Message={id:string;title:string;message:string;link?:string;audience?:string;read_at?:string|null;created_at:string;recipient_name?:string;recipient_email?:string};

export default function CommCenter(){
 const[u,setU]=useState<User|null>(null),[items,setItems]=useState<Message[]>([]),[teachers,setTeachers]=useState<User[]>([]),[students,setStudents]=useState<User[]>([]);
 const[title,setTitle]=useState(""),[message,setMessage]=useState(""),[audience,setAudience]=useState("ALL"),[userIds,setUserIds]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sent,setSent]=useState("");
 async function load(){const m=await fetch("/api/me",{cache:"no-store"});const mj=await m.json();if(!mj.user){location.href="/login";return}setU(mj.user);const n=await fetch("/api/notifications",{cache:"no-store"});if(n.ok){const j=await n.json();setItems(j.items||[])}if(mj.user.role==="ADMIN"){const[t,s]=await Promise.all([fetch("/api/teachers",{cache:"no-store"}),fetch("/api/students",{cache:"no-store"})]);if(t.ok)setTeachers(await t.json());if(s.ok)setStudents(await s.json())}}
 useEffect(()=>{load()},[]);
 async function send(){setError("");setSent("");if(!title.trim()||!message.trim()){setError("Please enter a subject and message.");return}if(audience==="DIRECT"&&!userIds.length){setError("Please select at least one recipient.");return}setBusy(true);try{const r=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,message,audience,userIds})});const j=await r.json();if(!r.ok){setError(j.error||"Could not send message.");return}setTitle("");setMessage("");setUserIds([]);setSent("Message sent successfully to "+j.sent+" recipient"+(j.sent===1?"":"s")+".");await load()}catch{setError("Could not send message. Please try again.")}finally{setBusy(false)}}
 async function markRead(id:string){await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"markRead",notificationId:id})});setItems(v=>v.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x))}
 if(!u)return <main className="login"><div className="login-card">Loading…</div></main>;
 const isAdmin=u.role==="ADMIN";
 const recipients=audience==="TEACHERS"?teachers:audience==="STUDENTS"?students:[...teachers,...students];
 return <div className="shell"><aside className="sidebar"><div className="brand">Global English Academy</div><nav className="nav"><Link href="/dashboard">Dashboard</Link><Link href="/dashboard/comm-center">Comm Centre</Link><Link href="/dashboard/records">History</Link><Link href="/change-password">Change Password</Link><button onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}}>Sign out</button></nav></aside>
 <main className="main"><div className="topbar"><div><h1>Comm Centre</h1><div className="muted">{isAdmin?"Admin communication centre":"System Messages"}</div></div><span className="badge">{u.role}</span></div>
 {isAdmin?<><section className="section"><h2>Send announcement</h2><p className="muted">Only Admin can send messages. Teachers and students can read messages but cannot reply.</p><div className="card"><label>Send to</label><select value={audience} onChange={e=>{setAudience(e.target.value);setUserIds([])}}><option value="ALL">All teachers and students</option><option value="TEACHERS">All teachers</option><option value="STUDENTS">All students</option><option value="DIRECT">Specific teacher/student</option></select>{audience==="DIRECT"&&<div style={{marginTop:12}}><label>Recipients</label><select multiple value={userIds} onChange={e=>setUserIds(Array.from(e.target.selectedOptions).map(o=>o.value))} style={{minHeight:130}}>{recipients.map(x=><option key={x.id} value={x.id}>{x.name} — {x.email}</option>)}</select></div>}<label style={{display:"block",marginTop:12}}>Subject</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. System Message" /><label style={{display:"block",marginTop:12}}>Message</label><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={6} placeholder="Write your announcement…" /><div style={{display:"flex",gap:10,alignItems:"center",marginTop:12}}><button className="primary" disabled={busy} onClick={send}>{busy?"Sending…":"Send Message"}</button>{sent&&<span style={{color:"#15803d"}}>{sent}</span>}{error&&<span style={{color:"#b91c1c"}}>{error}</span>}</div></div></section><section className="section"><h2>Sent history</h2><table className="table"><thead><tr><th>Time</th><th>Subject</th><th>Audience</th><th>Recipient</th><th>Message</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.title}</td><td>{x.audience}</td><td>{x.recipient_name||x.recipient_email||"—"}</td><td>{x.message}</td></tr>)}{!items.length&&<tr><td colSpan={5}>No messages sent yet.</td></tr>}</tbody></table></section></>:<section className="section"><h2>System Message</h2><p className="muted">Messages from the Admin appear here. This section is read-only.</p><table className="table"><thead><tr><th>Time</th><th>Subject</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td><strong>{x.title}</strong><div className="muted" style={{marginTop:6,whiteSpace:"pre-wrap"}}>{x.message}</div></td><td>{x.read_at?"Read":"Unread"}</td><td>{!x.read_at&&<button onClick={()=>markRead(x.id)}>Mark as read</button>}</td></tr>)}{!items.length&&<tr><td colSpan={4}>No system messages.</td></tr>}</tbody></table></section>}</main></div></main></TeacherShell>}