import {Pool,QueryResultRow} from "pg";declare global{var __geaPool:Pool|undefined;var __geaSchemaReady:Promise<void>|undefined}
export const pool=global.__geaPool??new Pool({connectionString:process.env.DATABASE_URL,max:10});if(process.env.NODE_ENV!=="production")global.__geaPool=pool;
const schema=`
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text UNIQUE NOT NULL,password_hash text NOT NULL,full_name text NOT NULL,role text NOT NULL CHECK(role IN ('ADMIN','TEACHER','STUDENT','PARENT')),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS parent_students(parent_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,student_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(parent_id,student_id));
CREATE TABLE IF NOT EXISTS students(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,level text DEFAULT 'Beginner',notes text DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS teacher_availability(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,day_of_week int NOT NULL CHECK(day_of_week BETWEEN 0 AND 6),start_time time NOT NULL,end_time time NOT NULL,UNIQUE(teacher_id,day_of_week,start_time,end_time));
CREATE TABLE IF NOT EXISTS teacher_availability_exceptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,slot_date date NOT NULL,start_time time NOT NULL,UNIQUE(teacher_id,slot_date,start_time));
CREATE TABLE IF NOT EXISTS lessons(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id uuid NOT NULL REFERENCES users(id),student_id uuid NOT NULL REFERENCES users(id),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'SCHEDULED',room_code text UNIQUE NOT NULL,topic text DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS lesson_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lesson_id uuid UNIQUE NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,teacher_id uuid NOT NULL REFERENCES users(id),notes text DEFAULT '',homework text DEFAULT '',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS materials(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),title text NOT NULL,description text DEFAULT '',url text DEFAULT '',level text DEFAULT '',created_by uuid REFERENCES users(id),content_data text DEFAULT '',mime_type text DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS lesson_materials(lesson_id uuid NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,material_id uuid NOT NULL REFERENCES materials(id) ON DELETE CASCADE,PRIMARY KEY(lesson_id,material_id));
CREATE TABLE IF NOT EXISTS recordings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lesson_id uuid UNIQUE NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,storage_url text NOT NULL,duration_seconds int DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS classroom_signals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),room_code text NOT NULL,sender_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS cancellation_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lesson_id uuid UNIQUE NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,requested_by uuid NOT NULL REFERENCES users(id),reason text DEFAULT '',status text NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED')),reviewed_by uuid REFERENCES users(id),reviewed_at timestamptz);
CREATE TABLE IF NOT EXISTS school_branding(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_name text NOT NULL DEFAULT 'Global English Academy',logo_data text DEFAULT '',primary_color text NOT NULL DEFAULT '#1d4ed8',secondary_color text NOT NULL DEFAULT '#0f172a',accent_color text NOT NULL DEFAULT '#f59e0b',updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN ('ADMIN','TEACHER','STUDENT','PARENT'));
ALTER TABLE materials ADD COLUMN IF NOT EXISTS content_data text DEFAULT '';
ALTER TABLE materials ADD COLUMN IF NOT EXISTS mime_type text DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_lessons_teacher ON lessons(teacher_id,starts_at);CREATE INDEX IF NOT EXISTS idx_lessons_student ON lessons(student_id,starts_at);CREATE INDEX IF NOT EXISTS idx_signals_room ON classroom_signals(room_code,created_at);`;
export async function ensureSchema(){if(!global.__geaSchemaReady)global.__geaSchemaReady=pool.query(schema).then(()=>undefined);return global.__geaSchemaReady}
export async function query<T extends QueryResultRow=any>(text:string,values:any[]=[]){await ensureSchema();return pool.query<T>(text,values)}