import {Pool,QueryResultRow} from "pg";declare global{var __geaPool:Pool|undefined;var __geaSchemaReady:Promise<void>|undefined}
export const pool=global.__geaPool??new Pool({connectionString:process.env.DATABASE_URL,max:10});if(process.env.NODE_ENV!=="production")global.__geaPool=pool;
const schema=`
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text UNIQUE NOT NULL,password_hash text NOT NULL,full_name text NOT NULL,role text NOT NULL CHECK(role IN ('ADMIN','TEACHER','STUDENT','PARENT')),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS parent_students(parent_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,student_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(parent_id,student_id));
CREATE TABLE IF NOT EXISTS students(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,level text DEFAULT 'Beginner',notes text DEFAULT '',age int,starting_material_id uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS teacher_availability(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,day_of_week int NOT NULL CHECK(day_of_week BETWEEN 0 AND 6),start_time time NOT NULL,end_time time NOT NULL,UNIQUE(teacher_id,day_of_week,start_time,end_time));
CREATE TABLE IF NOT EXISTS teacher_availability_exceptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,slot_date date NOT NULL,start_time time NOT NULL,UNIQUE(teacher_id,slot_date,start_time));
CREATE TABLE IF NOT EXISTS teacher_availability_slots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,slot_date date NOT NULL,start_time time NOT NULL,end_time time NOT NULL,UNIQUE(teacher_id,slot_date,start_time));
CREATE TABLE IF NOT EXISTS lessons(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id uuid NOT NULL REFERENCES users(id),student_id uuid NOT NULL REFERENCES users(id),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'SCHEDULED',room_code text UNIQUE NOT NULL,topic text DEFAULT '',lesson_type text NOT NULL DEFAULT 'ONE_ON_ONE');
CREATE SEQUENCE IF NOT EXISTS lesson_class_number_seq AS bigint START WITH 1;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS class_number bigint;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS class_id text;
UPDATE lessons SET class_number=nextval('lesson_class_number_seq') WHERE class_number IS NULL;
SELECT setval('lesson_class_number_seq',COALESCE((SELECT MAX(class_number) FROM lessons),0)+1,false);
UPDATE lessons SET class_id='GEAO'||to_char(starts_at AT TIME ZONE 'Africa/Johannesburg','YYYYMMDD')||'/'||lpad(class_number::text,3,'0') WHERE class_id IS NULL;
ALTER TABLE lessons ALTER COLUMN class_number SET DEFAULT nextval('lesson_class_number_seq');
CREATE UNIQUE INDEX IF NOT EXISTS idx_lessons_class_number ON lessons(class_number);
CREATE UNIQUE INDEX IF NOT EXISTS idx_lessons_class_id ON lessons(class_id);
CREATE TABLE IF NOT EXISTS lesson_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lesson_id uuid UNIQUE NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,teacher_id uuid NOT NULL REFERENCES users(id),notes text DEFAULT '',homework text DEFAULT '',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE lesson_records ADD COLUMN IF NOT EXISTS scores jsonb NOT NULL DEFAULT '{}'::jsonb;ALTER TABLE lesson_records ADD COLUMN IF NOT EXISTS assessment text NOT NULL DEFAULT '';ALTER TABLE lesson_records ADD COLUMN IF NOT EXISTS report_status text NOT NULL DEFAULT 'FINISHED' CHECK(report_status IN ('FINISHED','UNFINISHED','NO_NEED'));
CREATE TABLE IF NOT EXISTS materials(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),title text NOT NULL,description text DEFAULT '',url text DEFAULT '',level text DEFAULT '',folder text DEFAULT 'Level 1',sequence_no int NOT NULL DEFAULT 1,created_by uuid REFERENCES users(id),content_data text DEFAULT '',mime_type text DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS lesson_materials(lesson_id uuid NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,material_id uuid NOT NULL REFERENCES materials(id) ON DELETE CASCADE,PRIMARY KEY(lesson_id,material_id));
CREATE TABLE IF NOT EXISTS recordings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lesson_id uuid UNIQUE NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,storage_url text NOT NULL,duration_seconds int DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS classroom_signals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),room_code text NOT NULL,sender_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS cancellation_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lesson_id uuid UNIQUE NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,requested_by uuid NOT NULL REFERENCES users(id),reason text DEFAULT '',status text NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED')),reviewed_by uuid REFERENCES users(id),reviewed_at timestamptz);
CREATE TABLE IF NOT EXISTS teacher_leave_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,lesson_id uuid REFERENCES lessons(id) ON DELETE CASCADE,leave_type text NOT NULL,reason text NOT NULL,document_data text DEFAULT '',document_name text DEFAULT '',document_mime text DEFAULT '',status text NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED')),reviewed_by uuid REFERENCES users(id),reviewed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS school_branding(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),school_name text NOT NULL DEFAULT 'Global English Academy',logo_data text DEFAULT '',primary_color text NOT NULL DEFAULT '#1d4ed8',secondary_color text NOT NULL DEFAULT '#0f172a',accent_color text NOT NULL DEFAULT '#f59e0b',updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,title text NOT NULL,message text NOT NULL,link text DEFAULT '',read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS password_reset_tokens(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash text UNIQUE NOT NULL,expires_at timestamptz NOT NULL,used_at timestamptz);
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN ('ADMIN','TEACHER','STUDENT','PARENT'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false;
ALTER TABLE students ADD COLUMN IF NOT EXISTS age int;ALTER TABLE students ADD COLUMN IF NOT EXISTS starting_material_id uuid;ALTER TABLE students DROP CONSTRAINT IF EXISTS students_starting_material_fk;ALTER TABLE students ADD CONSTRAINT students_starting_material_fk FOREIGN KEY(starting_material_id) REFERENCES materials(id) ON DELETE SET NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS ferris_wheel_material_id uuid REFERENCES materials(id) ON DELETE SET NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS demo_enabled boolean NOT NULL DEFAULT true;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS content_data text DEFAULT '';ALTER TABLE materials ADD COLUMN IF NOT EXISTS mime_type text DEFAULT '';ALTER TABLE materials ADD COLUMN IF NOT EXISTS folder text DEFAULT 'Level 1';ALTER TABLE materials ADD COLUMN IF NOT EXISTS sequence_no int DEFAULT 1;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS lesson_type text NOT NULL DEFAULT 'ONE_ON_ONE';
CREATE INDEX IF NOT EXISTS idx_lessons_teacher ON lessons(teacher_id,starts_at);CREATE INDEX IF NOT EXISTS idx_lessons_student ON lessons(student_id,starts_at);CREATE INDEX IF NOT EXISTS idx_signals_room ON classroom_signals(room_code,created_at);CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens(user_id);CREATE INDEX IF NOT EXISTS idx_teacher_leave_lesson ON teacher_leave_requests(lesson_id,status);CREATE INDEX IF NOT EXISTS idx_teacher_leave_teacher ON teacher_leave_requests(teacher_id,created_at);
`;
export async function ensureSchema(){if(!global.__geaSchemaReady)global.__geaSchemaReady=pool.query(schema).then(()=>undefined);return global.__geaSchemaReady}
export async function query<T extends QueryResultRow=any>(text:string,values:any[]=[]){await ensureSchema();return pool.query<T>(text,values)}