"use client";
import{useEffect,useState}from"react";
export default function RateTeachers(){const[rows,setRows]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[start,setStart]=useState(""),[end,setEnd]=useState(""),[teacher,setTeacher]=useState(""),[saving,setSaving]=useState<string|null>(null);
async function load(q=""){const x=await fetch("/api/teacher-ratings"+q,{cache:"no-store"});if(x.ok){const j=await x.json();setRows(j.rows||[]);setTeachers(j.teachers||[])}}
useEffect(()=>{load()},[]);
function filter(){const p=new URLSearchParams();if(start)p.set("start",start);if(end)p.set("end",end);if(teacher)p.set("teacher",teacher);load("?"+p.toString())}
async function rate(id:string,rating:number){setSaving(id);const x=await fetch("/api/teacher-ratings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({lessonId:id,rating})});if(x.ok)await load();setSaving(null)}
return <main className="main"><div className="topbar"><div><h1>Rate Teachers</h1><div className="muted">Rate your teacher after each completed lesson.</div></div><div style={{textAlign:"right"}}><div className="muted">Classes</div><div style={{fontSize:28,fontWeight:800}}>{rows.length}</div></div></div>
<div className="card section"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr auto",gap:12,alignItems:"end"}}><label>Start Date<input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End Date<input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Teacher<select className="input" value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">All teachers</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><button className="primary" onClick={filter} disabled={!!(start&&end&&end<start)}>Filter</button></div></div>
<div className="section" style={{overflowX:"auto"}}><table className="table" style={{minWidth:950}}><thead><tr><th>#</th><th>Class ID</th><th>Start Time</th><th>End Time</th><th>Teacher</th><th>Rate 1–10</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.lesson_id}><td>{i+1}</td><td><strong>{r.class_id||"—"}</strong></td><td>{new Date(r.starts_at).toLocaleString()}</td><td>{new Date(r.ends_at).toLocaleString()}</td><td>{r.teacher_name}</td><td><div style={{display:"flex",gap:2,alignItems:"center"}}>{Array.from({length:10},(_,i)=><button key={i} type="button" title={String(i+1)} aria-label={"Rate "+(i+1)+" stars"} disabled={saving===r.lesson_id} onClick={()=>rate(r.lesson_id,i+1)} style={{border:0,background:"transparent",padding:1,cursor:"pointer",fontSize:27,lineHeight:1,color:r.rating&&i<r.rating?"#fff1a8":"#d1d5db"}}>★</button>)}</div>{r.rating&&<div className="muted" style={{fontSize:12}}>{r.rating}/10</div>}</td></tr>)}</tbody></table></div></main>}