"use client";
import{useEffect,useMemo,useState}from"react";
export default function ViewStudents(){
 const[rows,setRows]=useState<any[]>([]),[lessons,setLessons]=useState<any[]>([]),[search,setSearch]=useState(""),[selected,setSelected]=useState<any>(null);
 useEffect(()=>{Promise.all([fetch("/api/students",{cache:"no-store"}),fetch("/api/lessons",{cache:"no-store"})]).then(async([a,b])=>{setRows(a.ok?await a.json():[]);setLessons(b.ok?await b.json():[])})},[]);
 const filtered=useMemo(()=>{const terms=search.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);if(!terms.length)return rows;return rows.filter(r=>terms.some(q=>[r.name,r.email,r.country_code,r.timezone,r.level].filter(Boolean).join(" ").toLowerCase().includes(q)))},[rows,search]);
 const selectedLessons=selected?lessons.filter(l=>l.student_id===selected.id):[];
 const canceled=selectedLessons.filter(l=>l.status==="CANCELLED").length;
 return <main className="main"><div className="topbar"><div><h1>View Students</h1><p className="muted">All students registered on Global English Academy.</p></div><div className="badge">{filtered.length} shown</div></div>
 <div className="card section"><div style={{display:"flex",gap:10,alignItems:"center"}}><input className="input" style={{flex:1}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search students by name, email, country, level or time zone…"/><button className="primary" onClick={()=>setSearch(search.trim())}>Search</button></div><p className="muted small" style={{marginBottom:0}}>Search can match one or more students. Separate multiple names/search terms with commas.</p></div>
 <div className="section"><table className="table"><thead><tr><th>Photo</th><th>Student</th><th>Email</th><th>Level</th><th>Country</th><th>Time Zone</th><th>Start Date</th><th>Purchased</th><th>Booked</th><th>Un-booked</th><th>Canceled</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.profile_image?<img src={r.profile_image} alt="" style={{width:42,height:42,borderRadius:"50%",objectFit:"cover"}}/>:<div style={{width:42,height:42,borderRadius:"50%",background:"#e5e7eb",display:"grid",placeItems:"center",fontWeight:700}}>{r.name?.[0]}</div>}</td><td><strong>{r.name}</strong></td><td>{r.email}</td><td>{r.level||"—"}</td><td>{r.country_code||"—"}</td><td>{r.timezone||"—"}</td><td>{r.created_at?new Date(r.created_at).toLocaleString():"—"}</td><td>{r.purchased_classes??0}</td><td>{r.booked_classes??0}</td><td>{r.unbooked_classes??0}</td><td>{r.canceled_classes??0}</td><td><button className="secondary" onClick={()=>setSelected(r)}>View full information</button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="card">No students match your search.</div>}</div>
 {selected&&<div style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(15,23,42,.72)",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div className="card" style={{width:"min(1150px,100%)",maxHeight:"92vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2>{selected.name}</h2><p className="muted">Complete student profile and purchased-lesson history</p></div><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div>
 <div className="grid"><div className="card"><div className="muted">Email</div><strong>{selected.email}</strong></div><div className="card"><div className="muted">Age</div><strong>{selected.age??"—"}</strong></div><div className="card"><div className="muted">Level</div><strong>{selected.level||"—"}</strong></div><div className="card"><div className="muted">Country</div><strong>{selected.country_code||"—"}</strong></div><div className="card"><div className="muted">Time Zone</div><strong>{selected.timezone||"—"}</strong></div><div className="card"><div className="muted">Starting Date</div><strong>{selected.created_at?new Date(selected.created_at).toLocaleString():"—"}</strong></div><div className="card"><div className="muted">Starting Material</div><strong>{selected.starting_material||"Auto from level"}</strong></div><div className="card"><div className="muted">Ferris Wheel Material</div><strong>{selected.ferris_wheel_material||"—"}</strong></div><div className="card"><div className="muted">Demo</div><strong>{selected.demo_enabled?"Enabled":"Disabled"}</strong></div><div className="card"><div className="muted">Account Status</div><strong>{selected.active?"Active":"Inactive"}</strong></div></div>
 <h3 style={{marginTop:22}}>Lesson / Purchased Class History</h3><div className="grid"><div className="card"><div className="muted">Purchased Classes</div><strong>{selected.purchased_classes??0}</strong></div><div className="card"><div className="muted">Booked Classes</div><strong>{selected.booked_classes??0}</strong></div><div className="card"><div className="muted">Un-booked Classes</div><strong>{selected.unbooked_classes??0}</strong></div><div className="card"><div className="muted">Canceled Classes</div><strong>{selected.canceled_classes??0}</strong></div></div>
 {selectedLessons.length?<table className="table"><thead><tr><th>Class ID</th><th>Date</th><th>Start</th><th>End</th><th>Teacher</th><th>Lesson</th><th>Status</th><th>Late Cancel</th></tr></thead><tbody>{selectedLessons.map(l=><tr key={l.id}><td>{l.class_id||"—"}</td><td>{new Date(l.starts_at).toLocaleDateString()}</td><td>{new Date(l.starts_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</td><td>{new Date(l.ends_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</td><td>{l.teacher_name}</td><td>{l.material_title||l.topic||l.lesson_type||"—"}</td><td>{l.status}</td><td>{l.student_cancelled_late?"Yes":"No"}</td></tr>)}</tbody></table>:<p className="muted">No lesson history yet.</p>}
 </div></div>}</main>
}