"use client";
import{useEffect,useMemo,useState}from"react";
const pad=(n:number)=>String(n).padStart(2,"0");
const fmt=(d:Date)=>d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
function chinaInstant(date:string,time:string){return new Date(date+"T"+time+":00+08:00")}
function localParts(date:string,time:string,tz:string){const p=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(chinaInstant(date,time));const g=(t:string)=>p.find(x=>x.type===t)?.value||"00";return{date:g("year")+"-"+g("month")+"-"+g("day"),time:g("hour")+":"+g("minute")}}
function chinaParts(value:Date|string){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date(value));const g=(t:string)=>p.find(x=>x.type===t)?.value||"00";return{date:g("year")+"-"+g("month")+"-"+g("day"),time:g("hour")+":"+g("minute")}}
export default function GlobalCalendar({admin=false}:{admin?:boolean}){const[pref,setPref]=useState<any>({timezone:"Asia/Shanghai",country_code:"CN"}),[lessons,setLessons]=useState<any[]>([]),[slots,setSlots]=useState<any[]>([]),[week,setWeek]=useState(()=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-d.getDay());return d}),[busy,setBusy]=useState("");
async function load(){const[p,l,a]=await Promise.all([fetch("/api/preferences",{cache:"no-store"}),fetch("/api/lessons",{cache:"no-store"}),fetch("/api/availability",{cache:"no-store"})]);if(p.ok)setPref(await p.json());if(l.ok)setLessons(await l.json());if(a.ok)setSlots(await a.json())}
useEffect(()=>{load()},[]);
const dates=useMemo(()=>Array.from({length:7},(_,i)=>addDays(week,i)),[week]);
const rows=useMemo(()=>Array.from({length:48},(_,i)=>({h:Math.floor(i/2),min:i%2?30:0})),[]);
const lessonMap=useMemo(()=>{const m=new Map<string,any>();lessons.forEach(l=>{if(l.status!=="CANCELLED"){const p=chinaParts(l.starts_at);m.set(p.date+" "+p.time,l)}});return m},[lessons]);
const slotMap=useMemo(()=>new Set(slots.map(s=>String(s.slot_date).slice(0,10)+" "+String(s.start_time).slice(0,5))),[slots]);
async function openSlot(date:string,time:string){if(admin)return;setBusy(date+time);const r=await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slotDate:date,startTime:time})});if(!r.ok){const j=await r.json().catch(()=>({}));alert(j.error||"Could not open slot.")}else await load();setBusy("")}
async function cancelSlot(date:string,time:string){if(admin)return;setBusy(date+time);const r=await fetch("/api/availability?date="+encodeURIComponent(date)+"&startTime="+encodeURIComponent(time),{method:"DELETE"});if(!r.ok){const j=await r.json().catch(()=>({}));alert(j.error||"Could not close slot.")}else await load();setBusy("")}
function shift(n:number){setWeek(d=>addDays(d,n*7))}
const tz=pref.timezone||"Asia/Shanghai";
return <section className="card" style={{marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><div className="eyebrow">GLOBAL SCHOOL CALENDAR</div><h2 style={{marginBottom:4}}>{admin?"Admin Calendar":"Booking Time"}</h2><p className="muted" style={{marginTop:0}}><strong>Chinese Time</strong> is permanent. The second time column shows the selected country/time zone: <strong>{tz}</strong>.</p></div><div style={{display:"flex",gap:8}}><button onClick={()=>shift(-1)}>← Previous</button><button onClick={()=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-d.getDay());setWeek(d)}}>This Week</button><button onClick={()=>shift(1)}>Next →</button></div></div><div style={{overflowX:"auto",marginTop:14}}><table className="booking-calendar" style={{minWidth:1180}}><thead><tr><th className="time-head" style={{minWidth:120,position:"sticky",left:0,zIndex:3}}>Chinese Time</th><th className="time-head" style={{minWidth:150}}>Selected Country Time</th>{dates.map(d=><th key={fmt(d)}><div>{d.toLocaleDateString("en-US",{weekday:"short"})}</div><strong>{d.toLocaleDateString("en-US",{month:"short",day:"numeric"})}</strong></th>)}</tr></thead><tbody>{rows.map(({h,min})=>{const t=pad(h)+":"+pad(min);return <tr key={t}><td className="time-cell" style={{background:"var(--card,#fff)",position:"sticky",left:0,zIndex:2}}><strong>{t}</strong><div className="muted small">Chinese Time · UTC+08:00</div></td><td className="time-cell"><strong>{localParts(fmt(week),t,tz).time}</strong><div className="muted small">{localParts(fmt(week),t,tz).date===fmt(week)?"same day":localParts(fmt(week),t,tz).date<fmt(week)?"previous day":"next day"}</div></td>{dates.map(d=>{const date=fmt(d),key=date+" "+t,l=lessonMap.get(key),open=slotMap.has(key),busyKey=date+t;return <td key={date+t} className="schedule-cell">{l?<div style={{padding:7,borderRadius:7,background:"#ede9fe",border:"1px solid #e2e8f0"}}><strong>{t} · {l.student_name||"Lesson"}</strong>{admin&&<div className="muted small">{l.teacher_name||""}</div>}</div>:open?<div style={{padding:7,borderRadius:7,background:"#dbeafe",border:"1px solid #e2e8f0"}}><strong>{t}</strong><div className="muted small">Available</div>{!admin&&<button type="button" onClick={()=>cancelSlot(date,t)} disabled={busy===busyKey} style={{fontSize:11,marginTop:3}}>{busy===busyKey?"Closing…":"Close"}</button>}</div>:!admin?<button type="button" onClick={()=>openSlot(date,t)} disabled={busy===busyKey} style={{width:"100%",fontSize:11}}>{busy===busyKey?"Opening…":t+" Open"}</button>:<div className="muted small">{t}</div>}</td>})}</tr>})}</tbody></table></div><div className="muted small" style={{marginTop:10}}>Chinese Time is the permanent school reference. Every 30-minute row has separate Chinese and selected-country time blocks. Local dates are marked when the conversion crosses midnight.</div></section>}
