"use client";
import{useEffect,useMemo,useState}from"react";
const pad=(n:number)=>String(n).padStart(2,"0");
const fmt=(d:Date)=>d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
function chinaParts(value:Date|string){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date(value));const g=(t:string)=>p.find(x=>x.type===t)?.value||"00";return{date:g("year")+"-"+g("month")+"-"+g("day"),time:g("hour")+":"+g("minute")}}
function chinaInstant(date:string,time:string){return new Date(date+"T"+time+":00+08:00")}
function localLabel(date:string,time:string,tz:string){return new Intl.DateTimeFormat("en-GB",{timeZone:tz,hour:"2-digit",minute:"2-digit",hour12:false}).format(chinaInstant(date,time))}
export default function GlobalCalendar({admin=false}:{admin?:boolean}){const[pref,setPref]=useState<any>({timezone:"Asia/Shanghai",country_code:"CN"}),[lessons,setLessons]=useState<any[]>([]),[slots,setSlots]=useState<any[]>([]),[week,setWeek]=useState(()=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-d.getDay());return d}),[busy,setBusy]=useState("");
async function load(){const [p,l,a]=await Promise.all([fetch("/api/preferences",{cache:"no-store"}),fetch("/api/lessons",{cache:"no-store"}),fetch("/api/availability",{cache:"no-store"})]);if(p.ok)setPref(await p.json());if(l.ok)setLessons(await l.json());if(a.ok)setSlots(await a.json())}
useEffect(()=>{load()},[]);
const dates=useMemo(()=>Array.from({length:7},(_,i)=>addDays(week,i)),[week]);
const hours=Array.from({length:24},(_,i)=>i);
const lessonMap=useMemo(()=>{const m=new Map<string,any>();lessons.forEach(l=>{if(l.status!=="CANCELLED")m.set(chinaParts(l.starts_at).date+" "+chinaParts(l.starts_at).time,l)});return m},[lessons]);
const slotMap=useMemo(()=>new Set(slots.map(s=>String(s.slot_date).slice(0,10)+" "+String(s.start_time).slice(0,5))),[slots]);
async function openSlot(date:string,time:string){if(admin)return;setBusy(date+time);const r=await fetch("/api/availability",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slotDate:date,startTime:time})});if(!r.ok){const j=await r.json().catch(()=>({}));alert(j.error||"Could not open slot.")}else await load();setBusy("")}
async function cancelSlot(date:string,time:string){if(admin)return;setBusy(date+time);const r=await fetch("/api/availability?date="+encodeURIComponent(date)+"&startTime="+encodeURIComponent(time),{method:"DELETE"});if(!r.ok){const j=await r.json().catch(()=>({}));alert(j.error||"Could not close slot.")}else await load();setBusy("")}
function shift(n:number){setWeek(d=>addDays(d,n*7))}
return <section className="card" style={{marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><div className="eyebrow">GLOBAL SCHOOL CALENDAR</div><h2 style={{marginBottom:4}}>{admin?"Admin Calendar":"Booking Time"}</h2><p className="muted" style={{marginTop:0}}><strong>Chinese Time</strong> is permanent. Local times are calculated from <strong>{pref.timezone||"Asia/Shanghai"}</strong>.</p></div><div style={{display:"flex",gap:8}}><button onClick={()=>shift(-1)}>← Previous</button><button onClick={()=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-d.getDay());setWeek(d)}}>This Week</button><button onClick={()=>shift(1)}>Next →</button></div></div><div style={{overflowX:"auto",marginTop:14}}><table className="booking-calendar" style={{minWidth:1100}}><thead><tr><th className="time-head" style={{minWidth:115}}>Chinese Time</th>{dates.map(d=><th key={fmt(d)}><div>{d.toLocaleDateString("en-US",{weekday:"short"})}</div><strong>{d.toLocaleDateString("en-US",{month:"short",day:"numeric"})}</strong></th>)}</tr></thead><tbody>{hours.map(h=>{const row=pad(h)+":00";return <tr key={row}><td className="time-cell"><strong>{row}</strong><div className="muted small">CST · UTC+08:00</div></td>{dates.map(d=>{const date=fmt(d);return <td key={date+row} className="schedule-cell"><div style={{fontSize:11,fontWeight:700,marginBottom:5}}>Local: {localLabel(date,row,pref.timezone||"Asia/Shanghai")}</div>{[0,30].map(min=>{const t=pad(h)+":"+pad(min),key=date+" "+t,l=lessonMap.get(key),open=slotMap.has(key),busyKey=date+t;return <div key={t} style={{marginBottom:5,padding:5,borderRadius:7,background:l?"#ede9fe":open?"#dbeafe":"#f8fafc",border:"1px solid #e2e8f0"}}>{l?<div><strong>{t} · {l.student_name||"Lesson"}</strong>{admin&&<div className="muted small">{l.teacher_name||""}</div>}</div>:open?<div><strong>{t}</strong><div className="muted small">Available</div>{!admin&&<button type="button" onClick={()=>cancelSlot(date,t)} disabled={busy===busyKey} style={{fontSize:11,marginTop:3}}>{busy===busyKey?"Closing…":"Close"}</button>}</div>:!admin?<button type="button" onClick={()=>openSlot(date,t)} disabled={busy===busyKey} style={{width:"100%",fontSize:11}}>{busy===busyKey?"Opening…":t+" Open"}</button>:<div className="muted small">{t}</div>}</div>})}</td>})}</tr>})}</tbody></table></div><div className="muted small" style={{marginTop:10}}>Every lesson remains stored against the permanent Chinese Time reference. The local time shown in each calendar block changes automatically for the selected country/time zone, including daylight-saving changes where applicable.</div></section>}
